apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-environment-pvc
  namespace: biolyticsai-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard