apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-environment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-environment
  template:
    metadata:
      labels:
        app: dev-environment
    spec:
      containers:
      - name: code-server
        image: ghcr.io/biolytics-ai/k8s-dev-env/vscode-bastion-devcontainer:latest
        ports:
        - containerPort: 8080
